apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-portfolio
  template:
    metadata:
      labels:
        app: my-portfolio
    spec:
      containers:
      - name: portfolio-container
        #image: nginx:latest
        image: tonkung456/my-portfolio:latest
        ports:
        - containerPort: 3000
