apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: my-portfolio
  ports:
    - protocol: TCP
      port: 80
      #targetPort: 80
      targetPort: 3000
