name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    paths:
      - 'app/**'
      - '.github/workflows/deploy.yml'
    paths-ignore:
      - 'my-aws-projects/eks-cluster/**'
  workflow_run:
    workflows: [ "Terraform Automation" ]
    types: [completed]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # tags: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
          tags: ${{ secrets.DOCKER_USERNAME }}/my-portfolio:latest

      - name: Debug Secret Check
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo " ERROR: DISCORD_WEBHOOK is empty! Check your Repo Secrets."
            exit 1
          else
            echo "DISCORD_WEBHOOK is set."
          fi

      #- name: Discord Notification
      #  if: always()
      #  # env:
      #  #  MSG: "GitHub Action Update..."
      #  run: |
      #    MSG="**GitHub Actions Update** **Project:** my-portfolio **Status:** ${{ job.status }} **Branch:** ${{ github.ref_name }} **Check it out here:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      #    JSON_PAYLOAD=$(jq -n --arg msg "$MSG" '{content: $msg}')
      #    curl --fail -i -H "Content-Type: application/json" \
      #         -X POST \
      #         -d "$JSON_PAYLOAD" \
      #         "${{ secrets.DISCORD_WEBHOOK }}"

      - name: Docker Hub Notification
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "The Continuous Integration (CI) process is complete"
          title: "Docker Build & Push Status"
          description: |
            **Repository:** ${{ secrets.DOCKER_USERNAME }}/portfolio:latest
            **Status:** ${{ job.status == 'success' && 'Image Pushed! 📦' || 'Build Failed! 💥' }}
            **Tag:** `latest` and `${{ github.sha }}`
          color: ${{ job.status == 'success' && '0x3498db' || '0xff0000' }}

  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

    #  - name: Deploy to AWS EC2 via SSH
    #    uses: appleboy/ssh-action@master
    #    env:
    #      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}//my-portfolio:latest
    #    with:
    #      host: ${{ secrets.HOST }}
    #      username: ${{ secrets.USERNAME }}
    #      key: ${{ secrets.SSH_KEY }}
    #      env: DOCKER_IMAGE_NAME
    #      script: |
    #        # sudo docker pull ${{ secrets.DOCKER_HUB_URL }}
    #        sudo docker pull $DOCKER_IMAGE_NAME
    #        sudo docker stop my-portfolio || true
    #        sudo docker rm my-portfolio || true
    #
    #        # sudo docker run -d -p 3000:3000 --name my-portfolio ${{ secrets.DOCKER_HUB_URL }}
    #        sudo docker run -d -p 3000:3000 --name my-portfolio $DOCKER_IMAGE_NAME
    #
    #        sudo docker image prune -f

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --name tonkung-eks-cluster-v2 --region ap-southeast-1

      - name: Deploy to EKS
        working-directory: ./my-aws-projects/eks-cluster/k8s
        run: |
          kubectl apply -f deploy.yaml
          kubectl apply -f service.yaml
          kubectl rollout restart deployment portfolio-deployment

      - name: Debug Secret Check
        run: |
          if [ -z "${{ secrets.DISCORD_WEBHOOK }}" ]; then
            echo "ERROR: DISCORD_WEBHOOK is empty! Check your Repo Secrets."
            exit 1
          else
            echo "DISCORD_WEBHOOK is set."
          fi

      #- name: Discord Notification
      #  uses: sarisia/actions-status-discord@v1
      #  if: always()
      #  with:
      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
      #    status: ${{ job.status }}
      #    contant: "The system is reporting the deployment results."
      #    title: "Deployment Status"
      #    description: "***Project:*** Portfolio Next.js\n***Branch:*** ${{ github.ref_name }}\n***Status:*** ${{ job.status }}"
      #    color: ${{ job.status == 'success' && '0x00ff00' || '0xff0000' }}

      - name: Get LoadBalancer URL
        id: get_url
        run: |
          sleep 30
          URL=$(kubectl get svc portfolio-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "APP_URL=http://$URL" >> $GITHUB_ENV
          echo "The app address has been found: $URL"

      - name: Discord Notification (Success)
        uses: sarisia/actions-status-discord@v1
        if: success()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          contant: "The Continuous Deployment (CD) process is complete"
          title: "Cluster is Ready & App is Live"
          description: |
            **Project:** Portfolio Next.js
            **Status:** Online 🟢
            **Access URL:** ${{ env.APP_URL }}
          color: "0x00ff00"

      - name: Discord Notification (Failure)
        uses: sarisia/actions-status-discord@v1
        if: failure()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          content: "⚠️ Something went wrong during deployment."
          title: "Deployment Failed!"
          description: "Please check the logs in GitHub Actions immediately!"
          color: "0xff0000"
