name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}//my-portfolio:latest

      - name: Discord Notification
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content: "**GitHub Actions Update**\nProject: my-portfolio\nStatus: ${{ job.status }\nBranch: ${{ github.ref_name }}"}' \
               "${{ secrets.DISCORD_WEBHOOK }}"
